#https://docs.landscape.io/configuration.html

strictness: medium

autodetect: true

#max-line-length depend strictness (80 for very high, 100 for high, 160 for medium and below)
max-line-length: 160

requirements:
  - requirements.txt
    
doc-warnings: yes
test-warnings: yes

pep8:
  full: true    
    
ignore-paths:
  - documentation
  - config
  - os_specific
  - dlstats/tests
  - resources
  
ignore-patterns:
  - ^.*\.yml$
  
pep8:
  disable:
    #- E1002
    #- E226
    #- W293
    #- E302
    #- E41